# Generated by Django 2.2.7 on 2020-03-25 07:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Industry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=12, verbose_name='编号')),
                ('name', models.CharField(max_length=100, verbose_name='行业名称')),
                ('listorder', models.IntegerField(default=999, verbose_name='排序')),
                ('status', models.BooleanField(default=True, verbose_name='是否使用')),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='exercise.Industry', verbose_name='父级代码')),
            ],
        ),
        migrations.CreateModel(
            name='ChinaRegions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region_name', models.CharField(db_column='region_name', max_length=30, verbose_name='地区的名字(例如：广州市)')),
                ('old_name', models.CharField(default=None, max_length=30, verbose_name='曾使用过的旧名称')),
                ('status', models.BooleanField(default=True, verbose_name='是否使用')),
                ('belong_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='under_region', to='exercise.ChinaRegions', verbose_name='上级地区(反向关联为下级)')),
            ],
        ),
    ]
