# Generated by Django 2.2.7 on 2020-03-25 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0002_auto_20200325_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chinaregions',
            name='name',
            field=models.CharField(max_length=30, verbose_name='地区的名字(例如：广州市)'),
        ),
    ]
