# Generated by Django 2.2.7 on 2020-03-25 08:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0004_auto_20200325_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chinaregions',
            name='belong_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='under_region', to='exercise.ChinaRegions', verbose_name='上级地区(反向关联为下级)'),
        ),
    ]
