# Generated by Django 2.2.7 on 2020-04-02 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0006_auto_20200325_1649'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='industry',
            name='parent',
        ),
        migrations.DeleteModel(
            name='ChinaRegions',
        ),
        migrations.DeleteModel(
            name='Industry',
        ),
    ]
